// <auto-generated />
using System;
using Clob.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clob.Infrastructure.Migrations
{
    [DbContext(typeof(ClobDbContext))]
    partial class ClobDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clob.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceBrl")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("balance_brl");

                    b.Property<decimal>("BalanceBtc")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("balance_btc");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BalanceBrl = 2.5m,
                            BalanceBtc = 10000m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BalanceBrl = 0.5m,
                            BalanceBtc = 50000m
                        });
                });

            modelBuilder.Entity("Clob.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceBrl")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("price_brl");

                    b.Property<decimal>("PriceBtc")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("price_btc");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
